name = "JuDOInterface"
uuid = "d3b3f8d7-7cb8-4d66-8c6c-114c578a6a12"
authors = ["e-duar-do <72969764+e-duar-do@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
